version: '3.5'

services:
  mongodb:
    image: mongo:latest
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: admin
      MONGO_DATABASE: divo
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
    volumes:
      - mongodb-data:/data/db
    networks:
      - divo-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_CONFIG_NAME: application-development
      SPRING_CONFIG_ADDITIONAL_LOCATION: /config/
    volumes:
      - ./config:/config
    networks:
      - divo-network

networks:
  divo-network:

volumes:
  mongodb-data:

secrets:
  mongodb_root_password:
    file: ./config/.mongodb_root_password
  mongodb_root_username:
    file: ./config/.mongodb_root_username
  mongodb_password:
    file: ./config/.mongodb_password
  mongodb_username:
    file: ./config/.mongodb_username