version: '3.5'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.Mongodb
    image: "divoinua/auto-mongodb"
    secrets:
      - mongodb_root_password
      - mongodb_root_username
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodb-data:/data/db
    networks:
      - DIVONET

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    image: "divoinua/auto-backend"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_CONFIG_NAME: application-development
      SPRING_CONFIG_ADDITIONAL_LOCATION: /config/
    volumes:
      - ./config:/config
    networks:
      - DIVONET

  frontend:
    image: divoinua/auto-frontend:latest
    container_name: frontend
    depends_on:
      - spring-app
    ports:
      - "4200:80" # open in browser http://localhost:4200
    networks:
      - DIVONET

networks:
  DIVONET:

volumes:
  mongodb-data:

secrets:
  mongodb_root_password:
    file: ./config/.mongodb_root_password
  mongodb_root_username:
    file: ./config/.mongodb_root_username