name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: Set up Amazon Corretto 17
        with:
          distribution: 'corretto'
          java-version: '17'

      - run: ./gradlew build
        name: Build with Gradle

      - uses: actions/checkout@v4
        name: Build the Docker Image
      - run: docker build . --file Dockerfile --tag divo-auto:$(date +%s)
