name: Docker Image CI

on:
  pull_request:
    branches:
      - PRODUCTION

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Amazon Corretto 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag auto-backend:latest

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DIVO_BACKEND_DOCKERHUB_USERNAME }} -p ${{ secrets.DIVO_BACKEND_DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push divoinua/auto-backend:latest
