name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Set up Amazon Corretto 17
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Build the Docker Image
    - uses: actions/checkout@v4
    - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
